"""added lucky draw stat

Revision ID: 6a05440b30a5
Revises: 1946da18be90
Create Date: 2025-09-27 19:16:11.663722

"""

from typing import Sequence, Union

from alembic import op
import sqlmodel
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6a05440b30a5"
down_revision: Union[str, Sequence[str], None] = "1946da18be90"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("lucky_draw", sa.Column("last_draw", sa.DateTime(), nullable=False))
    op.alter_column(
        "users",
        "balance",
        existing_type=sa.NUMERIC(precision=12, scale=2),
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "balance",
        existing_type=sa.NUMERIC(precision=12, scale=2),
        nullable=True,
    )
    op.drop_column("lucky_draw", "last_draw")
    # ### end Alembic commands ###
